# Use a stable Debian base image
FROM debian:stable-slim

RUN apt-get update && apt-get install -y postfix libsasl2-modules ca-certificates && rm -rf /var/lib/apt/lists/*

COPY main.cf /etc/postfix/main.cf
COPY sasl_passwd /etc/postfix/sasl_passwd
COPY run.sh /run.sh

RUN chmod +x /run.sh

EXPOSE 25

CMD ["/run.sh"]
