name: Build, Test, and Notify with Custom Relay

on:
  push:
    branches:
      - develop
      - feature/EJ-50-local-smtp-server
  workflow_dispatch:

  pull_request:
    branches:
      - develop

jobs:
  build-test-and-notify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Builds the image for the SMTP server
      - name: Build Mail Relay Container
        run: docker build -t mail-relay ./email-smtp-local

      - name: List Docker Images After Build
        run: docker images

      - name: Run Mail Relay Container
        run: |
            docker run -d -p 1025:25 --name my-mail-relay -e SMTP_RELAY=$(echo "${{ secrets.SMTP_RELAY }}" | base64 --decode) -e SMTP_USERNAME=$(echo "${{ secrets.SMTP_USERNAME }}" | base64 --decode) -e SMTP_PASSWORD=$(echo "${{ secrets.SMTP_PASSWORD }}" | base64 --decode) mail-relay

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build and Test with Gradle
        run: ./gradlew build

      - name: Send Failure Notification
        if: failure()
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Run Email Client Script
        if: failure()
        run: python send_notification.py
        env:
          EMAIL_RECIPIENT: "ecommercedevbf@gmail.com"
          EMAIL_SUBJECT: "Build Failed in ${{ github.repository }}"
          EMAIL_BODY: |
            A build has failed in the ${{ github.repository }} repository.

            Branch: ${{ github.ref }}
            Commit: ${{ github.sha }}
            Author: ${{ github.actor }}

            Please review the failure at the following link:
            ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}